name: 'e2e tests'
description: '(debug) This is an action to run e2e tests on push.'
author: 'Meek Simbule <meekdenzo@gmail.com>'
branding:
  icon: 'search'
  color: 'white'

on:
  push:
    branches:
      - master
      - federation_v2

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Build all packages
        run: yarn nx run-many --target=build --all
      - name: Run E2E tests
        run: yarn docker up -d && yarn nx e2e example
